from __future__ import annotations

import argparse
import hashlib
import html
import json
import os
import re
import tempfile
import time
from collections import Counter
from urllib.parse import urljoin
from dataclasses import dataclass
from datetime import datetime, timezone
from html.parser import HTMLParser
from pathlib import Path
from typing import Any
from zoneinfo import ZoneInfo
import threading
from xml.etree import ElementTree as ET

import requests
from dotenv import load_dotenv
from yt_dlp import YoutubeDL
from youtube_transcript_api import YouTubeTranscriptApi


DEFAULT_CHANNEL_URL = "https://www.youtube.com/@AIDailyBrief/videos"
DEFAULT_SOURCES_FILE = Path(os.getenv("SOURCES_FILE", "sources.json"))
DEFAULT_OUTPUT_DIR = Path("reports")
DEFAULT_STATE_FILE = Path(".state/last_video.json")
DEFAULT_INTERVAL_HOURS = 8
DEFAULT_SUMMARY_MODEL = "gpt-4.1-mini"
DEFAULT_TRANSCRIPTION_MODEL = "whisper-1"
DEFAULT_NVIDIA_BASE_URL = "https://integrate.api.nvidia.com/v1"
DEFAULT_NVIDIA_MODEL = "meta/llama-3.3-70b-instruct"
DEFAULT_NVIDIA_TIMEOUT_SECONDS = 120
DEFAULT_OLLAMA_BASE_URL = "http://localhost:11434"
DEFAULT_OLLAMA_MODEL = "llama3.1"
DEFAULT_OLLAMA_TIMEOUT_SECONDS = 120
DEFAULT_HISTORY_LIMIT = 1000
PRAGUE_TIMEZONE = ZoneInfo("Europe/Prague")
DAILY_SEND_HOURS = {7, 20}
DAILY_USECASE_LIBRARY = [
    {
        "title": "AI triáž e-mailů",
        "audience": "menší týmy a founder",
        "problem": "třídění rutinních zpráv a návrhy odpovědí",
        "start": "napoj inbox na model, dej mu 3 kategorie a povol jen drafty",
        "benefit": "méně chaosu v inboxu a rychlejší reakce",
    },
    {
        "title": "AI hlídač konkurence",
        "audience": "marketing a founder",
        "problem": "sledování novinek, cen a release notes konkurence",
        "start": "propoj RSS, web a newslettery do jednoho denního shrnutí",
        "benefit": "rychlejší reakce na změny trhu",
    },
    {
        "title": "AI copy helper pro support",
        "audience": "zákaznická podpora",
        "problem": "návrhy odpovědí na opakující se dotazy",
        "start": "seřaď top 20 dotazů, vytvoř template a nechej AI doplnit konkrétní detaily",
        "benefit": "konzistentní odpovědi a kratší doba reakce",
    },
    {
        "title": "AI shrnutí dokumentů",
        "audience": "operativní a právní týmy",
        "problem": "dlouhé dokumenty a hledání důležitých bodů",
        "start": "pošli dokument do workflow a nech AI vracet stručné body a rizika",
        "benefit": "rychlejší orientace a méně přehlédnutých detailů",
    },
    {
        "title": "AI triáž e-shop požadavků",
        "audience": "e-commerce tým",
        "problem": "dotazy na sklad, doručení a vrácení",
        "start": "označ 5 nejčastějších intentů a AI použij jen na routing a draft odpovědi",
        "benefit": "méně ruční práce a rychlejší vyřízení",
    },
    {
        "title": "AI meeting notes",
        "audience": "produktové a sales týmy",
        "problem": "ruční zápis z meetingů a ztracené akční body",
        "start": "nahraj přepis, požádej o akce, rozhodnutí a rizika",
        "benefit": "lepší follow-up a méně zapomenutých úkolů",
    },
    {
        "title": "AI alerty na release notes",
        "audience": "product manager a QA",
        "problem": "sledování změn v produktech a API",
        "start": "sleduj release notes, diffy a changelogy a nech AI vytahovat breaking changes",
        "benefit": "rychlejší reakce na změny a menší riziko regresí",
    },
]
HOT_NEWS_KEYWORDS = {
    "breaking",
    "urgent",
    "launch",
    "launched",
    "release",
    "released",
    "announced",
    "announcement",
    "model",
    "gpt",
    "claude",
    "gemini",
    "llama",
    "openai",
    "anthropic",
    "google",
    "microsoft",
    "meta",
    "sora",
    "reasoning",
    "safety",
    "research",
}
BAD_SUMMARY_PHRASES = (
    "zdrojový text analyzován",
    "source text analyzed",
    "i'm happy to help",
    "please paste the text",
    "paste the text here",
    "here are the main points",
    "here are 5-8 concise",
    "here is a concise and accurate summary",
    "here is a summary of the text",
    "here is a summary",
    "here are 5-8 key takeaways",
    "the text appears to be a javascript file generated by next.js",
    "the text appears to be a javascript file",
    "a css file",
    "i need you to provide the text",
    "text je kód javascript",
    "showing up to 50 entries per page",
    "entries per page",
    "document.cookie.match",
    "window.matchmedia",
    "shrnutí:",
    "summary:",
)
WEEKLY_INTRO_PHRASES = (
    "here is",
    "here are",
    "zde jsou",
    "tady jsou",
    "summary:",
    "shrnutí:",
)
DEFAULT_TEST_SUBJECT = (
    "Testovací subjekt: Zkontroluj, že sumarizace a Telegram notifikace fungují. "
    "Tento text slouží jako umělý vstup pro ověření automatiky."
)

TELEGRAM_API_URL = "https://api.telegram.org/bot{token}/sendMessage"

STOPWORDS = {
    "a",
    "about",
    "after",
    "all",
    "also",
    "an",
    "and",
    "are",
    "as",
    "at",
    "be",
    "because",
    "been",
    "but",
    "by",
    "can",
    "could",
    "do",
    "does",
    "done",
    "for",
    "from",
    "had",
    "has",
    "have",
    "he",
    "her",
    "his",
    "how",
    "i",
    "if",
    "in",
    "into",
    "is",
    "it",
    "its",
    "just",
    "like",
    "me",
    "more",
    "most",
    "my",
    "no",
    "not",
    "of",
    "on",
    "one",
    "or",
    "our",
    "out",
    "over",
    "re",
    "s",
    "she",
    "so",
    "some",
    "than",
    "that",
    "the",
    "their",
    "them",
    "then",
    "there",
    "these",
    "they",
    "this",
    "to",
    "too",
    "under",
    "up",
    "was",
    "we",
    "were",
    "what",
    "when",
    "where",
    "which",
    "who",
    "will",
    "with",
    "would",
    "you",
    "your",
}


@dataclass(frozen=True)
class Settings:
    sources_file: Path
    output_dir: Path
    state_file: Path
    interval_hours: int
    summary_model: str
    transcription_model: str
    nvidia_base_url: str
    nvidia_model: str
    nvidia_timeout_seconds: int
    ollama_base_url: str
    ollama_model: str
    ollama_timeout_seconds: int
    openai_api_key: str | None
    nvidia_api_key: str | None
    telegram_bot_token: str | None
    telegram_chat_id: str | None
    telegram_admins: list[str] | None


@dataclass(frozen=True)
class SourceDefinition:
    type: str
    url: str
    name: str | None = None
    priority: int = 0


@dataclass(frozen=True)
class SourceSnapshot:
    source_key: str
    source_type: str
    source_name: str
    title: str
    url: str
    description: str
    fingerprint: str
    published_at: str | None
    content: str


@dataclass(frozen=True)
class UpdateRecord:
    source_key: str
    source_name: str
    source_type: str
    title: str
    url: str
    summary: str
    report_path: Path
    fingerprint: str


class HTMLTextExtractor(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self._parts: list[str] = []
        self._skip_depth = 0

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str]] | None = None) -> None:
        if tag.lower() in {"script", "style", "noscript"}:
            self._skip_depth += 1

    def handle_endtag(self, tag: str) -> None:
        if tag.lower() in {"script", "style", "noscript"} and self._skip_depth > 0:
            self._skip_depth -= 1

    def handle_data(self, data: str) -> None:
        if self._skip_depth > 0:
            return
        text = data.strip()
        if text:
            self._parts.append(text)

    def text(self) -> str:
        return " ".join(self._parts)


def load_settings() -> Settings:
    load_dotenv()
    return Settings(
        sources_file=Path(os.getenv("SOURCES_FILE", str(DEFAULT_SOURCES_FILE))),
        output_dir=Path(os.getenv("OUTPUT_DIR", str(DEFAULT_OUTPUT_DIR))),
        state_file=Path(os.getenv("STATE_FILE", str(DEFAULT_STATE_FILE))),
        interval_hours=int(os.getenv("CHECK_INTERVAL_HOURS", str(DEFAULT_INTERVAL_HOURS))),
        summary_model=os.getenv("OPENAI_SUMMARY_MODEL", DEFAULT_SUMMARY_MODEL),
        transcription_model=os.getenv("OPENAI_TRANSCRIPTION_MODEL", DEFAULT_TRANSCRIPTION_MODEL),
        nvidia_base_url=os.getenv("NVIDIA_BASE_URL", DEFAULT_NVIDIA_BASE_URL),
        nvidia_model=os.getenv("NVIDIA_MODEL", DEFAULT_NVIDIA_MODEL),
        nvidia_timeout_seconds=int(os.getenv("NVIDIA_TIMEOUT_SECONDS", str(DEFAULT_NVIDIA_TIMEOUT_SECONDS))),
        ollama_base_url=os.getenv("OLLAMA_BASE_URL", DEFAULT_OLLAMA_BASE_URL),
        ollama_model=os.getenv("OLLAMA_MODEL", DEFAULT_OLLAMA_MODEL),
        ollama_timeout_seconds=int(os.getenv("OLLAMA_TIMEOUT_SECONDS", str(DEFAULT_OLLAMA_TIMEOUT_SECONDS))),
        openai_api_key=os.getenv("OPENAI_API_KEY"),
        nvidia_api_key=os.getenv("NVIDIA_API_KEY"),
        telegram_bot_token=os.getenv("TELEGRAM_BOT_TOKEN"),
        telegram_chat_id=os.getenv("TELEGRAM_CHAT_ID"),
        telegram_admins=[s.strip() for s in os.getenv("TELEGRAM_ADMIN_IDS", "").split(",") if s.strip()] or None,
    )


def load_state(state_file: Path) -> dict[str, Any]:
    if not state_file.exists():
        return {}
    return json.loads(state_file.read_text(encoding="utf-8"))


def save_state(state_file: Path, payload: dict[str, Any]) -> None:
    state_file.parent.mkdir(parents=True, exist_ok=True)
    state_file.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def load_sources(settings: Settings) -> list[SourceDefinition]:
    if settings.sources_file.exists():
        raw_sources = json.loads(settings.sources_file.read_text(encoding="utf-8"))
        if not isinstance(raw_sources, list):
            raise RuntimeError("SOURCES_FILE musí obsahovat JSON pole zdrojů.")

        sources: list[SourceDefinition] = []
        for raw_source in raw_sources:
            if not isinstance(raw_source, dict):
                continue
            source_type = str(raw_source.get("type") or "").strip().lower()
            source_url = str(raw_source.get("url") or "").strip()
            source_name = str(raw_source.get("name") or "").strip() or None
            priority_value = raw_source.get("priority")
            if not source_type or not source_url:
                continue
            try:
                priority = int(priority_value) if priority_value is not None else default_priority_for_type(source_type)
            except (TypeError, ValueError):
                priority = default_priority_for_type(source_type)
            sources.append(SourceDefinition(type=source_type, url=source_url, name=source_name, priority=priority))

        if not sources:
            raise RuntimeError(f"{settings.sources_file} neobsahuje žádné platné zdroje.")
        return sorted(sources, key=source_sort_key, reverse=True)

    return [
        SourceDefinition(
            type="youtube",
            url=os.getenv("YOUTUBE_CHANNEL_URL", DEFAULT_CHANNEL_URL),
            name="AIDailyBrief",
            priority=default_priority_for_type("youtube"),
        )
    ]


def default_priority_for_type(source_type: str) -> int:
    if source_type == "youtube":
        return 3
    if source_type in {"rss", "atom", "feed"}:
        return 3
    if source_type in {"web", "website", "page"}:
        return 1
    return 0


def source_sort_key(source: SourceDefinition) -> tuple[int, str, str]:
    return (source.priority, source.name or source.url, source.url)


def source_key(source: SourceDefinition) -> str:
    normalized_name = re.sub(r"[^a-z0-9]+", "-", (source.name or source.url).lower()).strip("-")
    normalized_url = hashlib.sha256(source.url.encode("utf-8")).hexdigest()[:8]
    return f"{source.type}:{normalized_name}:{normalized_url}"


def load_source_state(state_file: Path) -> dict[str, Any]:
    return load_state(state_file)


def save_source_state(state_file: Path, state: dict[str, Any]) -> None:
    save_state(state_file, state)


def fingerprint_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def make_safe_key(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9._-]+", "_", value).strip("_") or "report"


def clean_text(text: str) -> str:
    text = html.unescape(text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def extract_visible_text(html_text: str) -> str:
    extractor = HTMLTextExtractor()
    extractor.feed(html_text)
    return clean_text(extractor.text())


def extract_html_title(html_text: str) -> str:
    title_match = re.search(r"<title[^>]*>(.*?)</title>", html_text, flags=re.IGNORECASE | re.DOTALL)
    if title_match:
        return clean_text(title_match.group(1))
    og_title_match = re.search(
        r'<meta[^>]+property=["\']og:title["\'][^>]+content=["\']([^"\']+)["\']',
        html_text,
        flags=re.IGNORECASE,
    )
    if og_title_match:
        return clean_text(og_title_match.group(1))
    return "Bez názvu"


def build_report(source: SourceSnapshot, summary: str) -> str:
    published = source.published_at or "nezjištěno"
    generated_at = datetime.now(timezone.utc).isoformat()
    return (
        f"# {source.title}\n\n"
        f"- Zdroj: {source.source_name} ({source.source_type})\n"
        f"- URL: {source.url}\n"
        f"- Nahráno / publikováno: {published}\n"
        f"- Zpracováno: {generated_at}\n\n"
        "## Shrnutí\n\n"
        f"{summary}\n\n"
        "## Obsah\n\n"
        f"{source.content}\n"
    )


def telegram_escape(text: str) -> str:
    return html.escape(text, quote=True)


def is_bad_summary_output(text: str) -> bool:
    cleaned = text.strip().lower()
    if not cleaned:
        return True

    if any(phrase in cleaned for phrase in BAD_SUMMARY_PHRASES):
        return True

    if re.match(r"^(here is|here are)\b", cleaned):
        return True

    if re.match(r"^(const\s|function\s|document\.|window\.|<html|<!doctype|import\s)", cleaned):
        return True

    if cleaned.startswith("\"") or cleaned.startswith("'"):
        return True

    if len(cleaned) < 20:
        return True

    return False


def fallback_summary(text: str) -> str:
    return heuristic_summary(text)


def is_bad_history_summary(summary: str) -> bool:
    if is_bad_summary_output(summary):
        return True

    cleaned = summary.strip().lower()
    if cleaned.startswith("zdrojový text analyzován"):
        return True

    if "i'm happy to help" in cleaned:
        return True

    return False


def strip_weekly_preamble(text: str) -> str:
    cleaned = text.strip()
    if not cleaned:
        return cleaned

    lines = [line.strip() for line in cleaned.splitlines() if line.strip()]
    if not lines:
        return cleaned

    first_line = lines[0].lower()
    if any(first_line.startswith(prefix) for prefix in WEEKLY_INTRO_PHRASES):
        lines = lines[1:]

    cleaned = "\n".join(lines).strip()
    cleaned = re.sub(
        r"^(?:here is(?: a(?: concise and accurate)?)? summary of the text(?: in [^:]+)?|here are(?: the key takeaways| the main points| 5-8 key takeaways)?(?: from the text)?(?: in [^:]+)?)\s*[:\-–—]?\s*",
        "",
        cleaned,
        flags=re.IGNORECASE,
    )
    cleaned = re.sub(
        r"^(?:summary|shrnutí|textový shrnutí|shrnutí textu)\s*[:\-–—]\s*",
        "",
        cleaned,
        flags=re.IGNORECASE,
    )
    return cleaned.strip()


def clean_model_summary(text: str) -> str:
    cleaned = strip_weekly_preamble(text)
    return cleaned or text.strip()


def normalize_weekly_summary(summary: str, max_points: int = 7) -> str:
    cleaned = strip_weekly_preamble(summary)
    if not cleaned:
        return "- Shrnutí se nepodařilo vygenerovat."

    candidate_lines = [line.strip() for line in cleaned.splitlines() if line.strip()]
    points: list[str] = []

    def add_point(value: str) -> None:
        value = re.sub(r"^[\-•*\d\.)\s]+", "", value).strip()
        value = re.sub(
            r"^(?:here is(?: a(?: concise and accurate)?)? summary of the text(?: in [^:]+)?|here are(?: the key takeaways| the main points| 5-8 key takeaways)?(?: from the text)?(?: in [^:]+)?)\s*[:\-–—]?\s*",
            "",
            value,
            flags=re.IGNORECASE,
        ).strip()
        value = re.sub(r"^(?:summary|shrnutí|textový shrnutí|shrnutí textu)\s*[:\-–—]\s*", "", value, flags=re.IGNORECASE).strip()
        if value and value not in points:
            points.append(value)

    for line in candidate_lines:
        if re.match(r"^[\-•*\d\.)]\s*", line):
            if not is_bad_summary_output(line):
                add_point(line)
            continue
        if len(candidate_lines) == 1:
            for sentence in re.split(r"(?<=[.!?])\s+", line):
                sentence = sentence.strip()
                if sentence and not is_bad_summary_output(sentence):
                    add_point(sentence)
        else:
            if not is_bad_summary_output(line):
                add_point(line)

    if not points:
        for sentence in re.split(r"(?<=[.!?])\s+", cleaned):
            sentence = sentence.strip()
            if sentence and not is_bad_summary_output(sentence):
                add_point(sentence)

    if not points:
        return "- Shrnutí se nepodařilo vygenerovat."

    points = points[:max_points]
    return "\n".join(f"- {point}" for point in points)


def summary_to_complete_sentences(summary: str, max_sentences: int = 2) -> str:
    cleaned = strip_weekly_preamble(summary)
    if is_bad_summary_output(cleaned):
        return ""

    sentences = [sentence.strip() for sentence in re.split(r"(?<=[.!?])\s+", cleaned) if sentence.strip()]
    if not sentences:
        return ""

    result_sentences: list[str] = []
    for sentence in sentences:
        sentence = re.sub(r"^[\-•*\d\.)\s]+", "", sentence).strip()
        if sentence:
            result_sentences.append(sentence)
        if len(result_sentences) >= max_sentences:
            break

    if not result_sentences:
        return ""

    return " ".join(result_sentences)


def sanitize_summary_for_weekly(summary: str, max_sentences: int = 2) -> str:
    return summary_to_complete_sentences(summary, max_sentences=max_sentences)


def summarize_text_with_model(
    text: str,
    settings: Settings,
    system_prompt: str,
    user_prompt: str,
) -> str:
    if settings.openai_api_key:
        try:
            from openai import OpenAI

            client = OpenAI(api_key=settings.openai_api_key)
            response = client.chat.completions.create(
                model=settings.summary_model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": f"{user_prompt}\n\n{text}"},
                ],
            )
            content = str(response.choices[0].message.content).strip()
            if content and not is_bad_summary_output(content):
                return clean_model_summary(content)
            if content:
                print("⚠ OpenAI vrátila nekvalitní shrnutí, používám fallback.")
        except Exception as exc:
            print(f"⚠ OpenAI shrnutí selhalo, přecházím na Ollamu: {exc}")

    if settings.nvidia_api_key:
        try:
            response = requests.post(
                f"{settings.nvidia_base_url.rstrip('/')}/chat/completions",
                headers={
                    "Authorization": f"Bearer {settings.nvidia_api_key}",
                    "Content-Type": "application/json",
                },
                json={
                    "model": settings.nvidia_model,
                    "messages": [
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": f"{user_prompt}\n\n{text}"},
                    ],
                    "temperature": 0.2,
                    "top_p": 0.9,
                    "max_tokens": 900,
                },
                timeout=settings.nvidia_timeout_seconds,
            )
            response.raise_for_status()
            payload = response.json()
            choices = payload.get("choices") or []
            content = str(((choices[0] if choices else {}) or {}).get("message", {}).get("content") or "").strip()
            if content and not is_bad_summary_output(content):
                return clean_model_summary(content)
            if content:
                print("⚠ NVIDIA vrátila nekvalitní shrnutí, používám fallback.")
        except Exception as exc:
            print(f"⚠ NVIDIA shrnutí selhalo, přecházím na Ollamu: {exc}")

    try:
        response = requests.post(
            f"{settings.ollama_base_url.rstrip('/')}/api/chat",
            json={
                "model": settings.ollama_model,
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": f"{user_prompt}\n\n{text}"},
                ],
                "stream": False,
                "options": {"temperature": 0.2},
            },
            timeout=settings.ollama_timeout_seconds,
        )
        response.raise_for_status()
        payload = response.json()
        content = str((payload.get("message") or {}).get("content") or "").strip()
        if content and not is_bad_summary_output(content):
            return clean_model_summary(content)
        if content:
            print("⚠ Ollama vrátila nekvalitní shrnutí, používám fallback.")
        raise RuntimeError("Ollama vrátila prázdné shrnutí.")
    except Exception as exc:
        print(f"⚠ Ollama shrnutí selhalo, používám lokální heuristiku: {exc}")
        return fallback_summary(text)


def compact_summary(summary: str, max_lines: int = 3, max_chars: int = 320) -> str:
    lines = [line.strip() for line in summary.splitlines() if line.strip()]
    cleaned: list[str] = []

    for line in lines:
        line = re.sub(r"^[\-•\*\d\.)\s]+", "", line).strip()
        if line:
            cleaned.append(line)
        if len(cleaned) >= max_lines:
            break

    if not cleaned:
        cleaned = [summary.strip()]

    short_text = " ".join(cleaned)
    if len(short_text) > max_chars:
        short_text = short_text[: max_chars - 1].rstrip() + "…"

    return short_text


def summarize_content(text: str, settings: Settings) -> str:
    return summarize_text_with_model(
        text,
        settings,
        system_prompt="Jsi analytik, který z textu vytváří stručné a přesné shrnutí v češtině.",
        user_prompt="Vrať 5 až 8 odrážek, buď věcný, neopakuj se a zdůrazni dopady nebo doporučení, pokud jsou v textu.",
    )


def fetch_youtube_snapshot(source: SourceDefinition) -> SourceSnapshot:
    ydl_options = {
        "quiet": True,
        "extract_flat": "in_playlist",
        "skip_download": True,
        "noplaylist": False,
    }

    with YoutubeDL(ydl_options) as ydl:
        info = ydl.extract_info(source.url, download=False)

    entries = [entry for entry in (info.get("entries") or []) if entry]
    if not entries:
        raise RuntimeError(f"Na kanálu {source.url} jsem nenašel žádná videa.")

    latest = entries[0]
    url = resolve_video_url(latest)
    title = str(latest.get("title") or "Bez názvu")
    description = str(latest.get("description") or "")
    published_at = normalize_uploaded_at(latest)
    content = description
    fingerprint = latest.get("id") or extract_video_id(url)
    source_name = source.name or title

    return SourceSnapshot(
        source_key=source_key(source),
        source_type="youtube",
        source_name=source_name,
        title=title,
        url=url,
        description=description,
        fingerprint=str(fingerprint),
        published_at=published_at,
        content=content,
    )


def fetch_rss_snapshot(source: SourceDefinition) -> SourceSnapshot:
    response = requests.get(source.url, timeout=20)
    response.raise_for_status()
    root = ET.fromstring(response.text)

    namespace = {
        "atom": "http://www.w3.org/2005/Atom",
        "media": "http://search.yahoo.com/mrss/",
    }

    entry = root.find("channel/item")
    if entry is None:
        entry = root.find("atom:entry", namespace)
    if entry is None:
        raise RuntimeError(f"V RSS/Atom feedu {source.url} jsem nenašel žádnou položku.")

    def first_text(path_options: list[str]) -> str:
        for path in path_options:
            node = entry.find(path, namespace)
            if node is not None and node.text:
                return clean_text(node.text)
        return ""

    title = first_text(["title"]) or "Bez názvu"
    link = first_text(["link"]) 
    if not link:
        link_node = entry.find("link", namespace)
        if link_node is not None:
            link = clean_text(link_node.attrib.get("href", "")) or clean_text(link_node.text or "")

    summary = first_text(["description", "summary", "content", "media:description"])
    published_at = first_text(["pubDate", "published", "updated"])
    guid = first_text(["guid", "id"]) or link or title
    content = summary or title

    return SourceSnapshot(
        source_key=source_key(source),
        source_type="rss",
        source_name=source.name or source.url,
        title=title,
        url=link or source.url,
        description=summary,
        fingerprint=fingerprint_text(guid + "|" + summary),
        published_at=published_at or None,
        content=content,
    )


def fetch_webpage_snapshot(source: SourceDefinition) -> SourceSnapshot:
    response = requests.get(source.url, timeout=20, headers={"User-Agent": "Mozilla/5.0"})
    response.raise_for_status()
    page_html = response.text
    title = extract_html_title(page_html)
    text_content = extract_visible_text(page_html)
    excerpt = text_content[:12000]
    fingerprint = fingerprint_text(excerpt)

    return SourceSnapshot(
        source_key=source_key(source),
        source_type="web",
        source_name=source.name or title,
        title=title,
        url=source.url,
        description="",
        fingerprint=fingerprint,
        published_at=None,
        content=excerpt or title,
    )


def fetch_source_snapshot(source: SourceDefinition) -> SourceSnapshot:
    if source.type == "youtube":
        return fetch_youtube_snapshot(source)
    if source.type in {"rss", "feed", "atom"}:
        return fetch_rss_snapshot(source)
    if source.type in {"web", "website", "page"}:
        return fetch_webpage_snapshot(source)
    raise RuntimeError(f"Nepodporovaný typ zdroje: {source.type}")


def resolve_video_url(entry: dict[str, Any]) -> str:
    video_id = entry.get("id") or entry.get("url") or ""
    if isinstance(video_id, str) and re.fullmatch(r"[A-Za-z0-9_-]{11}", video_id):
        return f"https://www.youtube.com/watch?v={video_id}"

    url = entry.get("webpage_url") or entry.get("url") or ""
    if isinstance(url, str) and url.startswith("http"):
        return url

    if isinstance(video_id, str) and video_id:
        return f"https://www.youtube.com/watch?v={video_id}"

    raise RuntimeError("Nepodařilo se zkonstruovat URL videa z dat kanálu.")


def fetch_latest_video(channel_url: str) -> VideoInfo:
    ydl_options = {
        "quiet": True,
        "extract_flat": "in_playlist",
        "skip_download": True,
        "noplaylist": False,
    }

    with YoutubeDL(ydl_options) as ydl:
        info = ydl.extract_info(channel_url, download=False)

    entries = [entry for entry in (info.get("entries") or []) if entry]
    if not entries:
        raise RuntimeError(f"Na kanálu {channel_url} jsem nenašel žádná videa.")

    latest = entries[0]
    url = resolve_video_url(latest)
    video_id = str(latest.get("id") or extract_video_id(url))
    title = str(latest.get("title") or "Bez názvu")
    description = str(latest.get("description") or "")
    uploaded_at = normalize_uploaded_at(latest)

    return VideoInfo(
        video_id=video_id,
        title=title,
        url=url,
        description=description,
        uploaded_at=uploaded_at,
    )


def extract_video_id(url: str) -> str:
    match = re.search(r"(?:v=|/)([A-Za-z0-9_-]{11})(?:[?&/]|$)", url)
    if not match:
        raise RuntimeError(f"Nepodařilo se z URL získat ID videa: {url}")
    return match.group(1)


def normalize_uploaded_at(entry: dict[str, Any]) -> str | None:
    timestamp = entry.get("timestamp")
    if isinstance(timestamp, (int, float)):
        return datetime.fromtimestamp(timestamp, tz=timezone.utc).isoformat()

    upload_date = entry.get("upload_date")
    if isinstance(upload_date, str) and re.fullmatch(r"\d{8}", upload_date):
        return datetime.strptime(upload_date, "%Y%m%d").replace(tzinfo=timezone.utc).isoformat()

    return None


def fetch_transcript(video_id: str) -> str:
    try:
        transcript_segments = YouTubeTranscriptApi.get_transcript(
            video_id,
            languages=["en", "en-US", "en-GB"],
        )
    except Exception:
        transcript_segments = YouTubeTranscriptApi.get_transcript(video_id)

    return "\n".join(segment["text"].strip() for segment in transcript_segments if segment.get("text"))


def fetch_subtitles_with_ytdlp(video_url: str) -> str:
    with tempfile.TemporaryDirectory(prefix="aidailybrief-subs-") as temp_dir_name:
        temp_dir = Path(temp_dir_name)
        ydl_options = {
            "quiet": True,
            "skip_download": True,
            "writeautomaticsub": True,
            "writesubtitles": True,
            "subtitlesformat": "vtt",
            "subtitleslangs": ["en", "en-US", "en-GB", "cs", "cs-CZ", "sk"],
            "outtmpl": str(temp_dir / "%(id)s.%(ext)s"),
        }

        with YoutubeDL(ydl_options) as ydl:
            ydl.extract_info(video_url, download=True)

        subtitle_files = sorted(temp_dir.glob("*.vtt"))
        if not subtitle_files:
            raise RuntimeError("Nepodařilo se stáhnout automatické titulky přes yt-dlp.")

        lines: list[str] = []
        for raw_line in subtitle_files[0].read_text(encoding="utf-8", errors="ignore").splitlines():
            line = raw_line.strip()
            if not line:
                continue
            if line == "WEBVTT" or line.startswith("NOTE"):
                continue
            if "-->" in line:
                continue
            if re.fullmatch(r"\d+", line):
                continue
            line = re.sub(r"<[^>]+>", "", line)
            if lines and lines[-1] == line:
                continue
            lines.append(line)

        transcript = "\n".join(lines).strip()
        if not transcript:
            raise RuntimeError("Stažené titulky jsou prázdné.")
        return transcript


def send_telegram_notification(bot_token: str, chat_id: str, video: VideoInfo, summary: str) -> None:
    if not bot_token or not chat_id:
        return

    message = (
        f"📺 *Nové video na kanálu AIDailyBrief*\n\n"
        f"*{video.title}*\n\n"
        f"🔗 [Podívej se na video]({video.url})\n\n"
        f"*Shrnutí:*\n{summary}\n\n"
        f"_Zpracováno automatizací_"
    )

    try:
        url = TELEGRAM_API_URL.format(token=bot_token)
        response = requests.post(
            url,
            json={
                "chat_id": chat_id,
                "text": message,
                "parse_mode": "Markdown",
                "disable_web_page_preview": False,
            },
            timeout=10,
        )
        if response.status_code != 200:
            print(f"⚠ Telegram notifikace selhala: {response.status_code} - {response.text}")
    except Exception as exc:
        print(f"⚠ Chyba při odesílání Telegram notifikace: {exc}")


def transcribe_with_openai(video_url: str, api_key: str, model: str) -> str:
    from openai import OpenAI

    client = OpenAI(api_key=api_key)
    with tempfile.TemporaryDirectory(prefix="aidailybrief-audio-") as temp_dir_name:
        temp_dir = Path(temp_dir_name)
        ydl_options = {
            "quiet": True,
            "noplaylist": True,
            "format": "bestaudio/best",
            "outtmpl": str(temp_dir / "%(id)s.%(ext)s"),
        }

        with YoutubeDL(ydl_options) as ydl:
            info = ydl.extract_info(video_url, download=True)
            audio_path = Path(ydl.prepare_filename(info))

        if not audio_path.exists():
            raise RuntimeError("Stažení zvuku pro přepis selhalo.")

        with audio_path.open("rb") as audio_file:
            response = client.audio.transcriptions.create(model=model, file=audio_file)

        return str(response.text).strip()


def summarize_with_openai(transcript: str, api_key: str, model: str) -> str:
    from openai import OpenAI

    client = OpenAI(api_key=api_key)
    response = client.chat.completions.create(
        model=model,
        messages=[
            {
                "role": "system",
                "content": "Jsi analytik, který z přepisu YouTube videa vytváří krátké a přesné shrnutí v češtině.",
            },
            {
                "role": "user",
                "content": (
                    "Z tohoto přepisu vytěž 5 až 8 nejdůležitějších bodů. "
                    "Použij odrážky, buď věcný, neopakuj se a zvýrazni dopady nebo doporučení, pokud jsou v textu.\n\n"
                    f"Přepis:\n{transcript}"
                ),
            },
        ],
    )
    return str(response.choices[0].message.content).strip()


def heuristic_summary(transcript: str, max_sentences: int = 6) -> str:
    sentences = [sentence.strip() for sentence in re.split(r"(?<=[.!?])\s+", transcript) if sentence.strip()]
    if not sentences:
        return "- Přepis je prázdný nebo se nepodařilo text rozdělit na věty."

    word_counts: Counter[str] = Counter()
    for sentence in sentences:
        for word in re.findall(r"[A-Za-z']+", sentence.lower()):
            if word not in STOPWORDS:
                word_counts[word] += 1

    if not word_counts:
        selected = sentences[:max_sentences]
    else:
        ranked_sentences = sorted(
            (
                (sum(word_counts[word] for word in re.findall(r"[A-Za-z']+", sentence.lower()) if word not in STOPWORDS), index, sentence)
                for index, sentence in enumerate(sentences)
            ),
            reverse=True,
        )
        selected = [sentence for _, _, sentence in sorted(ranked_sentences[:max_sentences], key=lambda item: item[1])]

    return "\n".join(f"- {sentence}" for sentence in selected)


def write_report(output_dir: Path, key: str, report_text: str) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    safe_key = make_safe_key(key)
    report_path = output_dir / f"{safe_key}.md"
    report_path.write_text(report_text, encoding="utf-8")
    return report_path


def process_source(source: SourceDefinition, settings: Settings, state: dict[str, Any]) -> UpdateRecord | None:
    snapshot = fetch_source_snapshot(source)
    stored_state = state.get("sources", {}).get(snapshot.source_key, {})
    if stored_state.get("fingerprint") == snapshot.fingerprint:
        return None

    body = snapshot.content or snapshot.description or snapshot.title
    summary = summarize_content(body, settings)
    report_text = build_report(snapshot, summary)
    report_path = write_report(settings.output_dir, snapshot.source_key, report_text)

    state.setdefault("sources", {})[snapshot.source_key] = {
        "fingerprint": snapshot.fingerprint,
        "title": snapshot.title,
        "url": snapshot.url,
        "source_type": snapshot.source_type,
        "source_name": snapshot.source_name,
        "priority": source.priority,
        "processed_at": datetime.now(timezone.utc).isoformat(),
        "report_path": str(report_path),
    }

    history_entry = {
        "source_key": snapshot.source_key,
        "source_name": snapshot.source_name,
        "source_type": snapshot.source_type,
        "priority": source.priority,
        "title": snapshot.title,
        "url": snapshot.url,
        "summary": summary,
        "report_path": str(report_path),
        "processed_at": datetime.now(timezone.utc).isoformat(),
        "fingerprint": snapshot.fingerprint,
    }
    history = state.setdefault("history", [])
    history.append(history_entry)
    if len(history) > DEFAULT_HISTORY_LIMIT:
        del history[:-DEFAULT_HISTORY_LIMIT]

    return UpdateRecord(
        source_key=snapshot.source_key,
        source_name=snapshot.source_name,
        source_type=snapshot.source_type,
        title=snapshot.title,
        url=snapshot.url,
        summary=summary,
        report_path=report_path,
        fingerprint=snapshot.fingerprint,
    )


def build_telegram_digest(updates: list[UpdateRecord]) -> str:
    lines = ["<b>Nové aktualizace</b>", ""]
    for update in updates:
        lines.extend(
            [
                f"• <b>{telegram_escape(update.source_name)}</b>",
                f"  <a href=\"{telegram_escape(update.url)}\">{telegram_escape(update.title)}</a>",
                f"  {telegram_escape(compact_summary(update.summary))}",
                f"  <i>{telegram_escape(update.source_type)}</i> · {telegram_escape(update.report_path.name)}",
                "",
            ]
        )
    lines.append("<i>Zpracováno automatizací</i>")
    return "\n".join(lines).strip()


def build_telegram_update_message(update: UpdateRecord, position: int | None = None, total: int | None = None) -> str:
    header_bits = ["<b>Novinka</b>"]
    if position is not None and total is not None and total > 1:
        header_bits.append(f"{position}/{total}")

    lines = [" · ".join(header_bits), ""]
    lines.extend(
        [
            f"<b>{telegram_escape(update.source_name)}</b>",
            f"<a href=\"{telegram_escape(update.url)}\">{telegram_escape(update.title)}</a>",
            f"{telegram_escape(compact_summary(update.summary, max_lines=4, max_chars=900))}",
            f"<i>{telegram_escape(update.source_type)}</i> · {telegram_escape(update.report_path.name)}",
            "<i>Zpracováno automatizací</i>",
        ]
    )
    return "\n".join(lines).strip()


def post_telegram_message(bot_token: str, chat_id: str, message: str) -> requests.Response:
    url = TELEGRAM_API_URL.format(token=bot_token)
    return requests.post(
        url,
        json={
            "chat_id": chat_id,
            "text": message,
            "parse_mode": "HTML",
            "disable_web_page_preview": False,
        },
        timeout=10,
    )


def send_telegram_text(bot_token: str, chat_id: str, message: str) -> None:
    if not bot_token or not chat_id or not message:
        return

    try:
        response = post_telegram_message(bot_token, chat_id, message)
        if response.status_code == 200:
            return

        if response.status_code == 400:
            try:
                payload = response.json()
            except Exception:
                payload = {}

            migrated_chat_id = payload.get("parameters", {}).get("migrate_to_chat_id")
            if migrated_chat_id:
                migrated_response = post_telegram_message(bot_token, str(migrated_chat_id), message)
                if migrated_response.status_code == 200:
                    print(f"⚠ Telegram chat byl migrován na nové ID {migrated_chat_id}; zpráva byla odeslána na nové ID.")
                    return
                print(f"⚠ Telegram notifikace selhala i po migraci: {migrated_response.status_code} - {migrated_response.text}")
                return

        print(f"⚠ Telegram notifikace selhala: {response.status_code} - {response.text}")
    except Exception as exc:
        print(f"⚠ Chyba při odesílání Telegram notifikace: {exc}")


def send_telegram_digest(bot_token: str, chat_id: str, updates: list[UpdateRecord]) -> None:
    if not bot_token or not chat_id or not updates:
        return

    total = len(updates)
    for index, update in enumerate(updates, start=1):
        send_telegram_text(bot_token, chat_id, build_telegram_update_message(update, index, total))


def prague_now() -> datetime:
    return datetime.now(PRAGUE_TIMEZONE)


def is_daily_send_window(now: datetime | None = None) -> bool:
    current = now or prague_now()
    return current.hour in DAILY_SEND_HOURS


def normalize_update_payload(update: UpdateRecord) -> dict[str, Any]:
    return {
        "source_key": update.source_key,
        "source_name": update.source_name,
        "source_type": update.source_type,
        "title": update.title,
        "url": update.url,
        "summary": update.summary,
        "report_path": str(update.report_path),
        "fingerprint": update.fingerprint,
    }


def update_from_payload(payload: dict[str, Any]) -> UpdateRecord | None:
    try:
        return UpdateRecord(
            source_key=str(payload.get("source_key") or ""),
            source_name=str(payload.get("source_name") or ""),
            source_type=str(payload.get("source_type") or ""),
            title=str(payload.get("title") or ""),
            url=str(payload.get("url") or ""),
            summary=str(payload.get("summary") or ""),
            report_path=Path(str(payload.get("report_path") or "report.md")),
            fingerprint=str(payload.get("fingerprint") or ""),
        )
    except Exception:
        return None


def is_hot_update(update: UpdateRecord) -> bool:
    source_boost = update.source_type.lower() in {"youtube", "rss", "feed", "atom"} and update.source_name.lower() in {
        "openai",
        "anthropic",
        "google",
        "microsoft",
        "meta",
    }
    if source_boost:
        return True

    text = f"{update.source_name} {update.title} {update.summary}".lower()
    if any(keyword in text for keyword in HOT_NEWS_KEYWORDS):
        return True

    return update.source_type.lower() == "youtube" and update.summary.count("\n") <= 2 and len(update.summary) < 400


def pending_updates_key() -> str:
    return "pending_updates"


def load_pending_updates(state: dict[str, Any]) -> list[UpdateRecord]:
    raw_pending = state.get(pending_updates_key(), [])
    if not isinstance(raw_pending, list):
        return []

    pending: list[UpdateRecord] = []
    for raw_item in raw_pending:
        if not isinstance(raw_item, dict):
            continue
        update = update_from_payload(raw_item)
        if update is not None:
            pending.append(update)
    return pending


def save_pending_updates(state: dict[str, Any], updates: list[UpdateRecord]) -> None:
    state[pending_updates_key()] = [normalize_update_payload(update) for update in updates]


def merge_updates(existing: list[UpdateRecord], new_items: list[UpdateRecord]) -> list[UpdateRecord]:
    seen: set[str] = set()
    merged: list[UpdateRecord] = []

    for item in [*existing, *new_items]:
        key = item.fingerprint or item.url or item.title
        if key in seen:
            continue
        seen.add(key)
        merged.append(item)

    return merged


def send_simple_reply(bot_token: str | None, chat_id: str | None, text: str) -> None:
    if not bot_token or not chat_id or not text:
        return
    try:
        post_telegram_message(bot_token, chat_id, text)
    except Exception as exc:
        print(f"⚠ Chyba při odeslání odpovědi v Telegramu: {exc}")


def get_status_text(settings: Settings) -> str:
    try:
        state = load_source_state(settings.state_file)
    except Exception:
        return "Stav není dostupný (chyba při čtení souboru stavu)."

    last = None
    history = state.get("history") if isinstance(state.get("history"), list) else None
    if history:
        last = history[-1]
    else:
        sources = state.get("sources") if isinstance(state.get("sources"), dict) else None
        if sources:
            latest = None
            for v in sources.values():
                p = v.get("processed_at")
                if p and (latest is None or p > latest):
                    latest = p
            if latest:
                last = {"processed_at": latest}

    if not last:
        return "Nebyl nalezen žádný záznam stavu."

    title = str(last.get("title") or last.get("source_name") or "(bez názvu)")
    processed = str(last.get("processed_at") or "neznámé")
    return f"Poslední zpracování: {title} — {processed}"


def poll_telegram_commands(settings: Settings) -> None:
    if not settings.telegram_bot_token:
        print("Telegram poller: TELEGRAM_BOT_TOKEN není nastaven, poller nebude spuštěn.")
        return

    print("Spouštím Telegram poller (getUpdates).")
    offset = None
    last_command_ts: dict[str, float] = {}
    allowed = set(settings.telegram_admins or [])
    if not allowed and settings.telegram_chat_id:
        allowed = {str(settings.telegram_chat_id)}

    while True:
        try:
            params: dict[str, Any] = {"timeout": 30, "allowed_updates": ["message"]}
            if offset is not None:
                params["offset"] = offset
            url = f"https://api.telegram.org/bot{settings.telegram_bot_token}/getUpdates"
            resp = requests.get(url, params=params, timeout=40)
            resp.raise_for_status()
            payload = resp.json()
            for update in payload.get("result", []):
                offset = int(update.get("update_id", 0)) + 1
                message = update.get("message") or update.get("edited_message")
                if not message:
                    continue
                text = str(message.get("text") or "")
                chat = message.get("chat") or {}
                chat_id = str(chat.get("id"))
                from_user = message.get("from") or {}
                from_id = str(from_user.get("id"))

                if allowed and from_id not in allowed and chat_id not in allowed:
                    continue

                if not text.startswith("/"):
                    continue

                parts = text.strip().split(" ", 1)
                cmd = parts[0].lower()
                arg = parts[1].strip() if len(parts) > 1 else ""

                now = time.time()
                if now - last_command_ts.get(from_id, 0) < 2:
                    send_simple_reply(settings.telegram_bot_token, chat_id, "Příkaz je příliš brzy po předchozím, zkuste za chvíli.")
                    continue
                last_command_ts[from_id] = now

                if cmd in ("/help", "/start"):
                    help_text = (
                        "Dostupné příkazy:\n"
                        "/status — stručný stav posledního zpracování\n"
                        "/run_now — spustí okamžitou kontrolu zdrojů\n"
                        "/weekly — vygeneruje a pošle týdenní report\n"
                        "/test [text] — pošle testovací shrnutí z volitelného textu\n"
                        "/help — zobrazí tuto nápovědu\n"
                    )
                    send_simple_reply(settings.telegram_bot_token, chat_id, help_text)
                    continue

                if cmd == "/status":
                    send_simple_reply(settings.telegram_bot_token, chat_id, get_status_text(settings))
                    continue

                if cmd in ("/run_now", "/run"):
                    send_simple_reply(settings.telegram_bot_token, chat_id, "Spouštím kontrolu zdrojů na pozadí…")
                    def bg_all():
                        try:
                            res = process_all_sources(settings)
                            send_simple_reply(settings.telegram_bot_token, chat_id, f"Kontrola dokončena:\n{res}")
                        except Exception as e:
                            send_simple_reply(settings.telegram_bot_token, chat_id, f"Chyba: {e}")
                    threading.Thread(target=bg_all, daemon=True).start()
                    continue

                if cmd in ("/weekly", "/weekly_report"):
                    send_simple_reply(settings.telegram_bot_token, chat_id, "Vytvářím týdenní report na pozadí…")
                    def bg_weekly():
                        try:
                            res = process_weekly_report(settings)
                            send_simple_reply(settings.telegram_bot_token, chat_id, f"Týdenní report hotov:\n{res}")
                        except Exception as e:
                            send_simple_reply(settings.telegram_bot_token, chat_id, f"Chyba při týdenním reportu: {e}")
                    threading.Thread(target=bg_weekly, daemon=True).start()
                    continue

                if cmd == "/test":
                    send_simple_reply(settings.telegram_bot_token, chat_id, "Provádím testovací běh…")
                    def bg_test():
                        try:
                            res = process_test_run(settings, arg or "")
                            send_simple_reply(settings.telegram_bot_token, chat_id, f"Test hotov:\n{res}")
                        except Exception as e:
                            send_simple_reply(settings.telegram_bot_token, chat_id, f"Chyba při testu: {e}")
                    threading.Thread(target=bg_test, daemon=True).start()
                    continue

                send_simple_reply(settings.telegram_bot_token, chat_id, f"Neznámý příkaz: {cmd}. Pošlete /help pro seznam.")

        except Exception as exc:
            print(f"Telegram poller chyba: {exc}")
            time.sleep(5)


def process_all_sources(settings: Settings) -> str:
    sources = load_sources(settings)
    state = load_source_state(settings.state_file)
    updates: list[UpdateRecord] = []

    for source in sources:
        try:
            update = process_source(source, settings, state)
            if update is not None:
                updates.append(update)
        except Exception as exc:
            print(f"Chyba při zpracování zdroje {source.type} {source.url}: {exc}")

    pending_updates = load_pending_updates(state)
    current_window = is_daily_send_window()
    hot_updates = [update for update in updates if is_hot_update(update)]
    queued_updates = [update for update in updates if update not in hot_updates]

    if hot_updates:
        send_telegram_digest(settings.telegram_bot_token or "", settings.telegram_chat_id or "", hot_updates)

    if current_window:
        to_send_now = merge_updates(pending_updates, queued_updates)
        if to_send_now:
            send_telegram_digest(settings.telegram_bot_token or "", settings.telegram_chat_id or "", to_send_now)
        save_pending_updates(state, [])
    else:
        save_pending_updates(state, merge_updates(pending_updates, queued_updates))

    save_source_state(settings.state_file, state)

    if not updates:
        if current_window and pending_updates:
            return f"Žádné nové aktualizace v monitorovaných zdrojích. Odesláno {len(pending_updates)} čekajících položek v pražském okně."
        if pending_updates:
            return f"Žádné nové aktualizace v monitorovaných zdrojích. {len(pending_updates)} položek čeká na odeslání v 7:00 nebo 20:00 pražského času."
        return "Žádné nové aktualizace v monitorovaných zdrojích."

    return "\n".join(
        [
            f"Zpracováno nových aktualizací: {len(updates)}",
            f"Pražské odesílací okno: {'ano' if current_window else 'ne'}",
            f"Hot novinky: {len(hot_updates)}",
            f"Čekající položky: {len(load_pending_updates(state))}",
            *[f"- {update.source_name}: {update.title} -> {update.report_path}" for update in updates],
        ]
    )


def compact_weekly_point(entry: dict[str, Any]) -> str:
    title = str(entry.get("title") or "Bez názvu")
    source_name = str(entry.get("source_name") or entry.get("source_type") or "zdroj")
    summary = sanitize_summary_for_weekly(str(entry.get("summary") or ""), max_sentences=2)
    if summary:
        return f"- {source_name}: {title} — {summary}"
    return f"- {source_name}: {title}"


def build_weekly_digest(entries: list[dict[str, Any]], weekly_summary: str) -> str:
    lines = ["<b>Top 7 news of the week</b>", ""]
    for entry in entries[:7]:
        source_name = telegram_escape(str(entry.get("source_name") or entry.get("source_type") or "zdroj"))
        title = telegram_escape(str(entry.get("title") or "Bez názvu"))
        lines.append(f"• <b>{source_name}</b>: {title}")
    lines.append("")
    lines.append(f"<i>Podrobnosti v reportu: {len(entries)} položek</i>")
    lines.append("<i>Zpracováno automatizací</i>")
    return "\n".join(lines).strip()


def process_weekly_report(settings: Settings) -> str:
    state = load_source_state(settings.state_file)
    history = state.get("history", [])
    if not isinstance(history, list) or not history:
        return "Týdenní report zatím nemá z čeho čerpat, protože historie je prázdná."

    now = datetime.now(timezone.utc)
    week_ago = now.timestamp() - 7 * 24 * 60 * 60
    recent_entries: list[dict[str, Any]] = []

    for entry in history:
        if not isinstance(entry, dict):
            continue
        processed_at = str(entry.get("processed_at") or "")
        try:
            processed_dt = datetime.fromisoformat(processed_at.replace("Z", "+00:00"))
        except Exception:
            continue
        if processed_dt.timestamp() >= week_ago:
            recent_entries.append(entry)

    if not recent_entries:
        return "Za posledních 7 dní v historii zatím nejsou žádné položky."

    recent_entries = [
        entry
        for entry in recent_entries
        if not is_bad_history_summary(str(entry.get("summary") or ""))
        and str(entry.get("title") or "").strip().lower() not in {"bez názvu", "", "bez nazvu"}
    ]

    if not recent_entries:
        return "Za posledních 7 dní jsou v historii jen nekvalitní nebo prázdné položky, takže z nich nejde sestavit použitelný weekly report."

    recent_entries.sort(
        key=lambda item: (
            int(item.get("priority") or 0),
            str(item.get("processed_at") or ""),
        ),
        reverse=True,
    )

    weekly_summary = normalize_weekly_summary("\n".join(compact_weekly_point(entry) for entry in recent_entries[:7]), max_points=7)

    report_text = (
        f"# Top 7 news of the week\n\n"
        f"- Období: posledních 7 dní\n"
        f"- Vygenerováno: {datetime.now(timezone.utc).isoformat()}\n"
        f"- Počet položek: {len(recent_entries)}\n\n"
        "## Shrnutí\n\n"
        f"{weekly_summary}\n\n"
        "## Položky\n\n"
        + "\n".join(f"- {entry.get('source_name', 'zdroj')}: {entry.get('title', 'Bez názvu')}" for entry in recent_entries[:7])
        + "\n"
    )

    report_path = write_report(settings.output_dir, f"weekly_{datetime.now(timezone.utc).strftime('%Y%m%d')}", report_text)
    digest = build_weekly_digest(recent_entries, weekly_summary)
    send_telegram_text(settings.telegram_bot_token or "", settings.telegram_chat_id or "", digest)

    return (
        "Týdenní report dokončen.\n"
        f"- Položek v týdnu: {len(recent_entries)}\n"
        f"- Report: {report_path}\n\n"
        f"{digest}"
    )


def select_daily_usecase(now: datetime | None = None) -> dict[str, str]:
    current = now or prague_now()
    index = current.timetuple().tm_yday % len(DAILY_USECASE_LIBRARY)
    return DAILY_USECASE_LIBRARY[index]


def _parse_json_object(text: str) -> dict[str, Any] | None:
    cleaned = text.strip()
    if not cleaned:
        return None

    start = cleaned.find("{")
    end = cleaned.rfind("}")
    if start == -1 or end == -1 or end <= start:
        return None

    try:
        payload = json.loads(cleaned[start : end + 1])
    except Exception:
        return None

    return payload if isinstance(payload, dict) else None


def generate_daily_usecase_with_model(settings: Settings) -> dict[str, str] | None:
    if not settings.nvidia_api_key:
        return None

    options_text = "\n".join(
        f"- {item['title']} | {item['audience']} | {item['problem']} | {item['start']} | {item['benefit']}"
        for item in DAILY_USECASE_LIBRARY
    )
    prompt = (
        "Vyber jeden nejpraktičtější AI usecase z nabídky níže a vrať pouze validní JSON objekt s klíči "
        "title, audience, problem, start, benefit. Piš česky, bez úvodu, bez markdownu a bez vysvětlování.\n\n"
        f"Nabídka:\n{options_text}"
    )

    try:
        response = requests.post(
            f"{settings.nvidia_base_url.rstrip('/')}/chat/completions",
            headers={
                "Authorization": f"Bearer {settings.nvidia_api_key}",
                "Content-Type": "application/json",
            },
            json={
                "model": settings.nvidia_model,
                "messages": [
                    {"role": "system", "content": "Jsi editor krátkých českých AI usecase. Vracíš jen JSON."},
                    {"role": "user", "content": prompt},
                ],
                "temperature": 0.2,
                "top_p": 0.9,
                "max_tokens": 500,
            },
            timeout=settings.nvidia_timeout_seconds,
        )
        response.raise_for_status()
        payload = response.json()
        choices = payload.get("choices") or []
        content = str(((choices[0] if choices else {}) or {}).get("message", {}).get("content") or "")
        parsed = _parse_json_object(content)
        if not parsed:
            return None

        title = str(parsed.get("title") or "").strip()
        audience = str(parsed.get("audience") or "").strip()
        problem = str(parsed.get("problem") or "").strip()
        start = str(parsed.get("start") or "").strip()
        benefit = str(parsed.get("benefit") or "").strip()
        if not all([title, audience, problem, start, benefit]):
            return None

        return {
            "title": title,
            "audience": audience,
            "problem": problem,
            "start": start,
            "benefit": benefit,
        }
    except Exception as exc:
        print(f"⚠ NVIDIA daily usecase selhal, používám fallback: {exc}")
        return None


def build_daily_usecase_message(usecase: dict[str, str], report_name: str) -> str:
    return (
        "🚀 <b>AI usecase dne</b>\n\n"
        f"💡 <b>{telegram_escape(usecase['title'])}</b>\n\n"
        f"👤 <b>Pro koho:</b> {telegram_escape(usecase['audience'])}\n"
        f"🧩 <b>Co řeší:</b> {telegram_escape(usecase['problem'])}\n"
        f"🛠 <b>Jak začít:</b> {telegram_escape(usecase['start'])}\n"
        f"✨ <b>Přínos:</b> {telegram_escape(usecase['benefit'])}\n\n"
        f"📄 Detail v reportu: {telegram_escape(report_name)}\n\n"
        "<i>Posláno automatizací AIDailyBrief</i>"
    )


def process_daily_usecase(settings: Settings) -> str:
    usecase = generate_daily_usecase_with_model(settings) or select_daily_usecase()
    report_name = f"daily_usecase_{datetime.now(timezone.utc).strftime('%Y%m%d')}.md"
    report_text = (
        "# AI usecase dne\n\n"
        f"- Datum: {datetime.now(timezone.utc).isoformat()}\n"
        f"- Název: {usecase['title']}\n"
        f"- Pro koho: {usecase['audience']}\n"
        f"- Co řeší: {usecase['problem']}\n"
        f"- Jak začít: {usecase['start']}\n"
        f"- Přínos: {usecase['benefit']}\n"
    )
    report_path = write_report(settings.output_dir, f"daily_usecase_{datetime.now(timezone.utc).strftime('%Y%m%d')}", report_text)
    message = build_daily_usecase_message(usecase, report_path.name)
    send_telegram_text(settings.telegram_bot_token or "", settings.telegram_chat_id or "", message)
    return (
        "Denní usecase dokončen.\n"
        f"- Report: {report_path}\n\n"
        f"{message}"
    )


def process_test_run(settings: Settings, subject: str) -> str:
    test_subject = subject.strip() or DEFAULT_TEST_SUBJECT
    test_source_key = f"test:{fingerprint_text(test_subject)[:12]}"
    test_source = SourceSnapshot(
        source_key=test_source_key,
        source_type="test",
        source_name="Testovací režim",
        title="Test sumarizace a Telegram notifikace",
        url="https://example.com/test",
        description="",
        fingerprint=fingerprint_text(test_subject),
        published_at=datetime.now(timezone.utc).isoformat(),
        content=test_subject,
    )
    summary = summarize_content(test_subject, settings)
    report_text = build_report(test_source, summary)
    report_path = write_report(settings.output_dir, f"test_{test_source_key}", report_text)
    update = UpdateRecord(
        source_key=test_source_key,
        source_name=test_source.source_name,
        source_type=test_source.source_type,
        title=test_source.title,
        url=test_source.url,
        summary=summary,
        report_path=report_path,
        fingerprint=test_source.fingerprint,
    )
    send_telegram_digest(settings.telegram_bot_token or "", settings.telegram_chat_id or "", [update])
    return (
        "Testovací běh dokončen.\n"
        f"- Subject: {test_subject}\n"
        f"- Summary: {summary}\n"
        f"- Report: {report_path}"
    )


def run_once(settings: Settings, test_mode: bool = False, test_subject: str = "") -> int:
    try:
        message = process_test_run(settings, test_subject) if test_mode else process_all_sources(settings)
        print(message)
        return 0
    except Exception as exc:
        print(f"Chyba: {exc}")
        return 1


def run_daemon(settings: Settings) -> int:
    interval_seconds = max(1, settings.interval_hours * 60 * 60)
    print(
        f"Spouštím nepřetržité sledování zdrojů ze {settings.sources_file} každých {settings.interval_hours} hodin."
    )

    while True:
        started_at = datetime.now(timezone.utc)
        print(f"[{started_at.isoformat()}] Kontrola nového videa...")
        exit_code = run_once(settings)
        print(f"[{datetime.now(timezone.utc).isoformat()}] Další kontrola za {settings.interval_hours} hodin.")
        if exit_code != 0:
            print("Běh pokračuje i po chybě, aby se další kontrola nespustila až po ručním zásahu.")
        time.sleep(interval_seconds)

    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Kontroluje kanál @AIDailyBrief, stáhne přepis posledního nového videa a vytvoří shrnutí."
    )
    parser.add_argument(
        "--daemon",
        action="store_true",
        help="Spustí nekonečnou smyčku s kontrolou v intervalu nastaveném proměnnou CHECK_INTERVAL_HOURS.",
    )
    parser.add_argument(
        "--interval-hours",
        type=int,
        default=None,
        help="Přepíše interval kontroly v hodinách pro aktuální spuštění.",
    )
    parser.add_argument(
        "--test",
        action="store_true",
        help="Spustí testovací režim, který pošle do Telegramu shrnutí umělého subjektu místo kontroly zdrojů.",
    )
    parser.add_argument(
        "--test-subject",
        type=str,
        default=DEFAULT_TEST_SUBJECT,
        help="Text, ze kterého se v testovacím režimu vytvoří shrnutí.",
    )
    parser.add_argument(
        "--weekly-report",
        action="store_true",
        help="Vytvoří týdenní report z historie posledních 7 dní a pošle ho do Telegramu.",
    )
    parser.add_argument(
        "--daily-usecase",
        action="store_true",
        help="Vytvoří denní AI usecase a pošle ho do Telegramu.",
    )
    parser.add_argument(
        "--telegram-poller",
        action="store_true",
        help="Spustí dlouhý poller, který naslouchá příkazům v Telegramu pomocí getUpdates.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    settings = load_settings()

    if args.interval_hours is not None:
        settings = Settings(
            sources_file=settings.sources_file,
            output_dir=settings.output_dir,
            state_file=settings.state_file,
            interval_hours=args.interval_hours,
            summary_model=settings.summary_model,
            transcription_model=settings.transcription_model,
            nvidia_base_url=settings.nvidia_base_url,
            nvidia_model=settings.nvidia_model,
            nvidia_timeout_seconds=settings.nvidia_timeout_seconds,
            ollama_base_url=settings.ollama_base_url,
            ollama_model=settings.ollama_model,
            ollama_timeout_seconds=settings.ollama_timeout_seconds,
            openai_api_key=settings.openai_api_key,
            nvidia_api_key=settings.nvidia_api_key,
            telegram_bot_token=settings.telegram_bot_token,
            telegram_chat_id=settings.telegram_chat_id,
            telegram_admins=settings.telegram_admins,
        )

    if args.test:
        return run_once(settings, test_mode=True, test_subject=args.test_subject)

    if args.weekly_report:
        try:
            message = process_weekly_report(settings)
            print(message)
            return 0
        except Exception as exc:
            print(f"Chyba při týdenním reportu: {exc}")
            return 1

    if args.daily_usecase:
        try:
            message = process_daily_usecase(settings)
            print(message)
            return 0
        except Exception as exc:
            print(f"Chyba při denním usecase: {exc}")
            return 1

    if args.daemon:
        return run_daemon(settings)

    if getattr(args, "telegram_poller", False):
        try:
            poll_telegram_commands(settings)
            return 0
        except KeyboardInterrupt:
            print("Telegram poller byl přerušen uživatelem.")
            return 0

    return run_once(settings)


if __name__ == "__main__":
    raise SystemExit(main())

